### ISSUE TITLE
Allow any package to advertise itself as a plugin

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/plugincompat#16]
Currently, plugincompat uses a heuristic that plugins are all named with a "pytest-" prefix. However, the plugin API allows any package to advertise itself as a plugin by exposing a suitable entry point.  As a result, some projects which have useful plugins aren't included (e.g. [backports.unittest_mock](https://pypi.python.org/pypi/backports.unittest_mock) or [jaraco.mongodb](https://pypi.python.org/pypi/jaraco.mongodb)). I guess one could just create a slim wrapper around those in another package called "pytest-backports-unittest-mock" or similar, but that seems messy.

Furethermore, some packages like [pytest-runner](https://pypi.python.org/pypi/pytest-runner) aren't pytest plugins, but appear to be so according to the heuristic.

How about instead considering a technique whereby a project can declare it's "Pytest Plugin-ness" through package metadata? Since entry points aren't readily visible in package metadata, perhaps consider creating a Trove Classifier to authoritatively and cleanly indicate the presence of a pytest plugin?

**Comment by jaraco** [comment]
http://stackoverflow.com/questions/18338178/how-to-propose-a-new-trove-classifier-on-pypi

**Comment by jaraco** [comment]
I suggest "Framework :: Pytest :: Plugin"

**Comment by nicoddemus** [comment]
Thanks for the suggestion!

I like the idea, but I would like to keep the current behavior of considering "pytest-" as plugins, even with some false positives. It also seems very easy to implement.

@hpk42, any comments here?

**Comment by hpk42** [comment]
On Fri, Jun 12, 2015 at 12:09 -0700, Jason R. Coombs wrote:
> Currently, plugincompat uses a heuristic that plugins are all named with a "pytest-" prefix. However, the plugin API allows any package to advertise itself as a plugin by exposing a suitable entry point.  As a result, some projects which have useful plugins aren't included (e.g. [backports.unittest_mock](https://pypi.python.org/pypi/backports.unittest_mock) or [jaraco.mongodb](https://pypi.python.org/pypi/jaraco.mongodb). I guess one could just create a slim wrapper around those in another package called "pytest-backports-unittest-mock" or similar, but that seems messy.

i think that plugincompat could be refined to grep entrypoint information
out of projects, filtering out false positives, no?

holger

> Furethermore, some packages like pytest-runner aren't pytest plugins, but appear to be so according to the heuristic.
> 
> How about instead considering a technique whereby a project can declare it's "Pytest Plugin-ness" through package metadata? Since entry points aren't readily visible in package metadata, perhaps consider creating a Trove Classifier to authoritatively and cleanly indicate the presence of a pytest plugin?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/pytest-dev/plugincompat/issues/16

-- 
about me:    http://holgerkrekel.net/about-me/
contracting: http://merlinux.eu

**Comment by jaraco** [comment]
I should think that locating/downloading the source tarball would be a substantial amount of work than querying the metadata from PyPI. Perhaps PyPI should include the entry points in the advertised metadata. Until it does, I'd recommend using the metadata that is advertised.

**Comment by nicoddemus** [comment]
@jaraco is correct, there's direct support for querying PyPI for classifiers, while trying to parse entrypoints would have to download the source for all packages.

What you guys think, can I move this forward? Seems like a good idea to me. :smile:

**Comment by flub** [comment]
Seems like a good idea to me, I think it'd be great if you went ahead and applied for it.  I wouldn't expect the pypi maintainers to have serious objections.

**Comment by hpk42** [comment]
Sure, makes sense to have trove classifier and then advertise it and have it used for all pytest-dev plugins.

**Comment by tarpas** [comment]
I definitely like it.

**Comment by nicoddemus** [comment]
I will move this forward then, thanks for the feedback!

**Comment by nicoddemus** [comment]
Created a [request](https://bitbucket.org/pypa/pypi/issue/301) for this on the pypa repository, if anyone wants to watch/vote for. :wink:

**Comment by asottile** [comment]
via af71d7ecd37c9de: The search has been expanded to include the `Framework :: Pytest` classifier

**Comment by obestwalter** [comment]
oops, thought it was doing this already ... thanks @asottile :)
