### ISSUE TITLE
tox.ini dependencies not being recognized for pytest-mpl

### ISSUE THREAD

**Issue by astrofrog** [pytest-dev/plugincompat#18]
I'm the developer for the pytest-mpl plugin:

https://github.com/astrofrog/pytest-mpl

This plugin first appeared on plugincompat for version 0.2, which didn't have a tox.ini file. I've since added one in version 0.3, but it looks like the new file is not getting used because matplotlib doesn't get installed:

http://plugincompat.herokuapp.com/output/pytest-mpl-0.3?py=py34&pytest=2.6.4

Does the ``.tox`` folder need to be wiped clean for the change to take effect?

**Comment by nicoddemus** [comment]
Strange... not sure why that would happen. Here's [the code](https://github.com/pytest-dev/plugincompat/blob/master/run.py#L85) which executes the tests for the plugin.

> Does the .tox folder need to be wiped clean for the change to take effect?

Travis always runs this in a clean environment, so this shouldn't be needed.

**Comment by astrofrog** [comment]
Ah, ignore me, the tox.ini is missing from the tar file because I forgot to add it to the MANIFEST.in file...

**Comment by nicoddemus** [comment]
No problem! :smile: 

Cheers :beers:
