### ISSUE TITLE
Freeze requirements txt

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/plugincompat#23]
Freeze requirements to ensure the production slug matches the development environment.

https://www.kennethreitz.org/essays/a-better-pip-workflow

**Comment by mcsitter** [comment]
The requirements.txt is frozen. Should the dev requirements also be frozen?

**Comment by nicoddemus** [comment]
I think just the production requirements being frozen is OK.

I'm closing this then. 👍
