### ISSUE TITLE
Why restricted to sdist?

### ISSUE THREAD

**Issue by wimglenn** [pytest-dev/plugincompat#25]
Is there a reason? What if author want to publish bdist_wheel only?
Just curious (and perhaps it could be mentioned in readme that you must upload an sdist to index)

**Comment by nicoddemus** [comment]
Hi @wimglenn,

Mostly because we rely on projects having a `tox.ini` file, which is only present in sdists.

About mentioning that somewhere on the README it makes sense, would you like to submit a PR? 😁

**Comment by wimglenn** [comment]
Oh OK - didn't realize this project was actually executing each plugin test suite, but it makes sense.

The `OVERVIEW.md` says:

> If a plugin doesn't have a tox.ini file, we generate a simple tox.ini which just ensures that the plugin was installed successfully by running pytest --help.

But this is possible with bdist also, isn't it?

You might find more maintainers these days only using sdist if there needs to be extensions compiled..

**Comment by The-Compiler** [comment]
I'm not aware of any pytest plugins which need extensions - are there any?

**Comment by wimglenn** [comment]
I'm not aware either, and it's beside the point. The scripts look for projects doing CI with a tox.ini and making sdist avail, but it means that there can be some false negatives listed on [the website](http://plugincompat.herokuapp.com).

**Comment by wimglenn** [comment]
@nicoddemus   What do you think of giving a tick to a .whl with the correct filename tags (`{distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl`) which installs and displays in the `pytest --help` correctly?

**Comment by nicoddemus** [comment]
> What do you think of giving a tick to a .whl with the correct filename tags ({distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl) which installs and displays in the pytest --help correctly?

Sounds like a good compromise. Would you like to open a PR? Should be simple enough to implement.

I've been thinking how useful those ticks are in reality TBH, because they give too much false negatives... it might be better to just list the plugins and their descriptions, and which Python version they declare to support. I don't know.

**Comment by wimglenn** [comment]
I began to work on it but there were some little things I was fixing up until it seemed there was so many of these that they should go in separate PR (see https://github.com/pytest-dev/plugincompat/pull/26) so that it doesn't obscure the actual change too much.

But now it seems that travis-ci, as used to execute run.py and post results, is interfering with the PR builder. Could you untangle that so the PR builder is just executing the suite in test_web.py instead?
