### ISSUE TITLE
Outdated info

### ISSUE THREAD

**Issue by stas00** [pytest-dev/plugincompat#37]
Here is some info to update:

1. The same plugin is listed twice:

- pytest-nbsmoke
- nbsmoke

The second entry should remain, the first one deleted. (plugin was renamed)

2. pytest-ipynb is no longer maintained. so https://pypi.org/project/pytest-ipynb is 404. Yet, it's still a well functioning and useful plugin, so perhaps linking to its archived github project is better than removing it completely - perhaps someone will take over its maintenance. Link: https://github.com/zonca/pytest-ipynb

Thanks.

**Comment by nicoddemus** [comment]
Thanks @stas00!

All the plugin information is parsed directly from PyPI, so I will implement a simple black-list system to skip `pytest-nbsmoke`. I will think about the best way to override the URL of `pytest-ipynb` as well.

**Comment by stas00** [comment]
`pytest-ipynb` is no longer on pypi, so you don't need to do anything special about it since as you say it should get removed automatically.

**Comment by nicoddemus** [comment]
Oh OK. 👍
