### ISSUE TITLE
Try to weed out "Framework :: Pytest" false-positives

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/plugincompat#53]
It seems a lot of packages are using the `Framework :: Pytest` classifier even though they are not plugins, but only use pytest to test their own code. This generates a bunch of false positives that we should avoid showing.

**Comment by The-Compiler** [comment]
I've been thinking about this recently as well - but I'm not sure what we can do, other than a hand-written list of exceptions?

FWIW I've tried to track down some of the repos and submit a PR, but many of those don't seem to exist, so I only ended up with https://github.com/BotEX-Developers/botbase/pull/12.

**Comment by nicoddemus** [comment]
Yeah I'm not sure either, but a thought that occurred was:

For all packages that don't start with "pytest-" and declare `Framework :: Pytest`, look at the source tarball for sign of entry points (hand parsing `setup.py`, `setup.cfg`, etc).

Of course there are obvious drawbacks: false positives, manual parsing is tricky/might be flaky, etc., but in the end we might get better results than what we are having currently.

**Comment by nicoddemus** [comment]
Closed by https://github.com/pytest-dev/plugincompat/issues/66.
