### ISSUE TITLE
Add guide on how to run flask app locally for development

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/plugincompat#54]
Hi. I think it would be beneficial to have a 'running locally' guide for developers to show them how to run this application locally on their machines. Does such a guide exist? If not, could one be written?

I could attempt to write one and submit it as a pr, but I'm unfamiliar with this project so I'm not sure how accurate it would be.

**Comment by nicoddemus** [comment]
Hi @gnikonorov,

>  Does such a guide exist? If not, could one be written?

I don't think it does, but sure it is possible to write one.

> I could attempt to write one and submit it as a pr, but I'm unfamiliar with this project so I'm not sure how accurate it would be.

That would be great! It is a standard flask application using MongoDB. Feel free to tackle this, any inaccuracies we can discuss over a PR. 😁

**Comment by nicoddemus** [comment]
Closed by https://github.com/pytest-dev/plugincompat/issues/66.
