### ISSUE TITLE
Migrate from xmlrpc to PyPIJSON

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/plugincompat#61]
PyPI has introduced a new [JSON api](https://wiki.python.org/moin/PyPIJSON). As a result, the [xml-rpc api](https://warehouse.pypa.io/api-reference/xml-rpc.html) is being phased out.

SInce PyPI introduced rate limiting for the xml-rpc api ( see https://github.com/pytest-dev/plugincompat/pull/59 and https://github.com/pytest-dev/plugincompat/pull/60 ) it would make sense for us to migrate now since (a) the library is deprecated and (b) moving to JSON should provide performance gains

**Comment by nicoddemus** [comment]
Closed by https://github.com/pytest-dev/plugincompat/issues/66.
